version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Creating vault password file"
      - echo "Sailp0!nt123" > vaultpasswordfile
      - echo "Upgrading pip"
      - pip install --upgrade pip
      - echo "Installing ansible"
      - pip install ansible
      - echo "Installing Packer"
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.8.6/packer_1.8.6_linux_amd64.zip && unzip packer.zip
      - echo "Copying installer files from S3 into IIQ role folders"
  pre_build:
    commands:
      - echo "Copying IIQ install files"
      - aws s3 cp s3://codebuild-iiq-installer-files/identityiq-8.3.zip ansible/roles/identityiq/files/
      - aws s3 cp s3://codebuild-iiq-installer-files/identityiq-8.3p2.jar ansible/roles/identityiq/files/
      - echo "Copying packer plugin from S3 to avoid limit rate"
      - aws s3 cp s3://codebuild-iiq-installer-files/packer-plugin-amazon_v1.2.1_x5.0_linux_amd64.zip .
      - unzip packer-plugin-amazon_v1.2.1_x5.0_linux_amd64.zip
      - echo "Updating the repository"
      - apt-get update -y
      - echo "Packer init"
      - ./packer init -upgrade packer.pkr.hcl
      - echo "Validating the Packer template"
      - ./packer validate packer.pkr.hcl

  build:
    commands:
       - echo "Building the Packer template"
       - ./packer build packer.pkr.hcl
       - echo "Printing public key"
       - cat ./iiqhost_sailpoint_rsa.pub