---
- name: Include secret vars
  include_vars:
    file: secrets.yml


- name: Generate hosts file
  ansible.builtin.template:
    src=hosts.j2
    dest=/etc/hosts

- name: Set motd
  ansible.builtin.copy:
    src: motd
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'
 
- name: Copy HR files over
  ansible.builtin.copy: 
    src: HR
    dest: /var/tmp/
    owner: tomcat
    group: tomcat
    mode: '0644'

- name: Copy LDAP files over
  ansible.builtin.copy: 
    src: EnterpriseDirectory
    dest: /var/tmp/
    owner: tomcat
    group: tomcat
    mode: '0644'

- name: Setup HR App
  command: "{{ java_cmd }} console iiqBeans -c \"import setup.xml\""
  args:
    chdir: /var/tmp/HR
    stdin: |
      {{ iiq_admin_user }}
      {{ iiq_admin_password }}
  async: 1200
  poll: 5
  register: cmdout
  changed_when: cmdout.rc != 0

- name: Aggregate HR App
  command: "{{ java_cmd }} console iiqBeans -c \"run 'Aggregate HR Authoritative'\""
  args:
    chdir: /var/tmp/HR
    stdin: |
      {{ iiq_admin_user }}
      {{ iiq_admin_password }}
  async: 1200
  poll: 5
  register: cmdout
  changed_when: cmdout.rc != 0

- name: Run refresh
  command: "{{ java_cmd }} console iiqBeans -c \"run 'Maintain Manager Hierarchy'\""
  args:
    chdir: /var/tmp/HR
    stdin: |
      {{ iiq_admin_user }}
      {{ iiq_admin_password }}
  async: 1200
  poll: 5
  register: cmdout
  changed_when: cmdout.rc != 0

- name: Setup LDAP App
  command: "{{ java_cmd }} console iiqBeans -c \"import setup.xml\""
  args:
    chdir: /var/tmp/EnterpriseDirectory
    stdin: |
      {{ iiq_admin_user }}
      {{ iiq_admin_password }}
  async: 1200
  poll: 5
  register: out
  changed_when: out.rc != 0

- name: Aggregate LDAP Accounts
  command: "{{ java_cmd }} console iiqBeans -c \"run 'Aggregate Enterprise Directory Accounts'\""
  args:
    chdir: /var/tmp/EnterpriseDirectory
    stdin: |
      {{ iiq_admin_user }}
      {{ iiq_admin_password }}
  async: 1200
  poll: 5
  register: cmdout
  changed_when: cmdout.rc != 0

- name: Aggregate LDAP Groups
  command: "{{ java_cmd }} console iiqBeans -c \"run 'Aggregate Enterprise Directory Groups'\""
  args:
    chdir: /var/tmp/EnterpriseDirectory
    stdin: |
      {{ iiq_admin_user }}
      {{ iiq_admin_password }}
  async: 1200
  poll: 5
  register: cmdout
  changed_when: cmdout.rc != 0

# - name: Import SERI Identity ObjectConfig
