---
# Create sailpoint user
- name: Create a sailpoint user
  ansible.builtin.user:
    name: sailpoint
    groups: sudo
    shell: /usr/bin/bash

- name: Allow ssh key login for sailpoint
  ansible.posix.authorized_key:
    user: sailpoint
    state: present
    key: "{{ lookup('file', 'WimsPair.pub') }}"

- name: Allow ssh key login for admin
  ansible.posix.authorized_key:
    user: sailpoint
    state: present
    key: "{{ lookup('file', 'WimsPair.pub') }}"

- name: "Allow sailpoint user to sudo without a password"
  lineinfile:
    dest: "/etc/sudoers" # path: in version 2.3
    state: "present"
    regexp: "^sailpoint"
    line: "sailpoint ALL=(ALL) NOPASSWD: ALL"

# Done by packer and kickstart
# - name: Ensure necessary packages are installed.
#   ansible.builtin.package:
#     name: "{{ core_dependencies }}"
#     state: present
#     update_cache: yes
# 
- name: Install gnupg packages
  ansible.builtin.package:
    name: gnupg
    state: present
    update_cache: yes

- name: setup hostname
  command: hostnamectl set-hostname iiq.sailpointdemo.com